pipeline {
    agent any
    stages {
        stage('Create Kubernetes Cluster using eksctl') {
            steps {
                withAWS(region:'us-east-2', credentials: 'Jenkins') {
                    sh '''
						eksctl create cluster \
						--name kubecluster \
						--version 1.13 \
						--nodegroup-name standard-workers \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-east-2 \
						--zones us-east-2a \
						--zones us-east-2b \
						--zones us-east-2c \
					'''
                }
            }
        }
        stage('Create conf file cluster') {
			steps {
				withAWS(region:'us-east-2', credentials: 'Jenkins') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name kubecluster
					'''
				}
			}
		}

    }
}