pipeline {
	agent any
	stages {

		stage('Lint HTML') {
			steps {
				sh 'sudo tidy -q -e index.html'
			}
		}
		
		stage('Build Docker Image') {
			steps {			
					sh '''
						sudo docker build -t aravindb15/capstone .
					'''
			}
		}

		stage('Push Image To Dockerhub') {
			steps {				
					sh '''
						sudo cat ~/my_password.txt | docker login -u aravindb15 -p --password-stdin
						sudo docker push aravindb15/capstone
					'''				
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-west-2', credentials:'Jenkins') {
					sh '''
						sudo kubectl config use-context arn:aws:eks:us-west-2:947522261353:cluster/kubecluster
					'''
				}
			}
		}

		stage('Deploy blue container') {
			steps {
				withAWS(region:'us-west-2', credentials:'Jenkins') {
					sh '''
						sudo kubectl apply -f ./blue-controller.json
					'''
				}
			}
		}

		stage('Deploy green container') {
			steps {
				withAWS(region:'us-west-2', credentials:'Jenkins') {
					sh '''
						sudo kubectl apply -f ./green-controller.json
					'''
				}
			}
		}

		stage('Create the service in the cluster, redirect to blue') {
			steps {
				withAWS(region:'us-west-2', credentials:'Jenkins') {
					sh '''
						sudo kubectl apply -f ./blue-service.json
					'''
				}
			}
		}

		stage('Wait user approve') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('Create the service in the cluster, redirect to green') {
			steps {
				withAWS(region:'us-west-2', credentials:'Jenkins') {
					sh '''
						sudo kubectl apply -f ./green-service.json
					'''
				}
			}
		}

	}
}